# Generated by Django 5.1.7 on 2025-04-01 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(
                    choices=[
                        ('STARTER', 'Starter'),
                        ('MAIN', 'Main Course'),
                        ('DESSERT', 'Dessert'),
                        ('DRINK', 'Drink')
                    ],
                    max_length=50
                )),
                ('image', models.ImageField(
                    blank=True,
                    null=True,
                    upload_to='menu_items/'
                )),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(
                    choices=[
                        ('WINDOW', 'Window'),
                        ('BALCONY', 'Balcony'),
                        ('INSIDE', 'Inside'),
                        ('BAR', 'Bar Area')
                    ],
                    max_length=50
                )),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('party_size', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[
                        ('PENDING', 'Pending'),
                        ('CONFIRMED', 'Confirmed'),
                        ('CANCELLED', 'Cancelled')
                    ],
                    default='PENDING',
                    max_length=20
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
                ('table', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='booking.table'
                )),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=(
                            'table',
                            'booking_date',
                            'booking_time'
                        ),
                        name='unique_booking'
                    )
                ],
            },
        ),
    ]
